version: "3.7"

services:
  jekyll:
    working_dir: /srv/jekyll
    build: .
    command: bash -c "bundle install && bundle exec jekyll s --host 0.0.0.0"
    volumes:
      - .:/srv/jekyll
    ports: 
      - "4000:4000"
